asyncee/django-easy-select2

easy_select2/widgets.py
tests/test_widgets.py

Here are pull request for #24. All comments are welcome.

Fix #24. Static files management improved.

---

.travis.yml
tox.ini

updated travis config: added ubuntu(trusty) distro. installing p35 from deadsnake.
updated tox to cover py34, py35.

build errors fixed.

---

README.rst
docs/source/changelog.rst
setup.py

- updated readme and setup.py to reflect new version changes

VERSION UPDATE TO 1.4.0

---

README.rst
docs/source/changelog.rst
easy_select2/static/easy_select2/js/easy_select2.js
easy_select2/static/easy_select2/js/init.js

- mark_safe problem fixed
- added select2 plugin constructor argument support
- updated easy_select2() wrapper to JQuery plugin

issue-44: mark_safe problem fixed

---

README.rst
docs/source/changelog.rst
easy_select2/static/easy_select2/js/easy_select2.js
setup.py

- updated easy_select.js, DomNodeInserted binding added

fixed issue-45: dynamic initializations

---

README.rst
docs/source/changelog.rst
easy_select2/static/easy_select2/js/easy_select2.js
setup.py

- initializing select2 for tabular and stacked Inlines when no records were added previously

issue-45: bug fixed

---

README.rst
docs/source/changelog.rst
easy_select2/static/easy_select2/js/easy_select2.js
setup.py

- fixed pencil icon/edit button url __fk__ param updation in url on new select2 selections
- fixed updation of select2 selected value while adding a new item dynamically

issue-50: bug fixed - change/edit url next to field does not get updated

---

easy_select2/static/easy_select2/js/init.js

Avoid error with $ undefined:
> Uncaught TypeError: $ is not a function

Work with jQuery instead of depending on $

---

easy_select2/static/easy_select2/js/easy_select2.js

Listen to `formset:added` events to work around #52 
https://docs.djangoproject.com/en/1.9/ref/contrib/admin/javascript/
https://code.djangoproject.com/ticket/15760

Formset added

---

easy_select2/static/easy_select2/js/easy_select2.js

This is a little crude attempt to solve Issue #57

An edge case where select2 goes undetected

---

.travis.yml
setup.py
tox.ini

Not adding a change log entry right now to avoid conflicts with #67…

Activate support for Python 3.8

---

easy_select2/models.py
sampleproject/demoapp/tests.py
sampleproject/demoapp/views.py

Drop dummy files of little value

---

easy_select2/widgets.py
sampleproject/demoapp/admin.py
sampleproject/demoapp/migrations/0002_remove_note_mood.py
sampleproject/sampleproject/urls.py

Remove unused imports

---

docs/source/changelog.rst
docs/source/configuration.rst
easy_select2/widgets.py
tests/test_widgets.py

Same as `SELECT2_USE_BUNDLED_JQUERY`, except for Select2 but jQuery.

Support using Select2 assets of Django Admin

---

.github/dependabot.yml

Related: https://github.com/asyncee/django-easy-select2/pull/88#issuecomment-998195883

Actions: Make GitHub Dependabot keep our GitHub Actions up to date

---

.github/workflows/run_pre_commit.yml
.travis.yml
easy_select2/forms.py
setup.py
tox.ini

Fix #86 and #87 
Also I added python 3.9 / 3.10 (I could remove this if needed)

Added Django 4.0 support.

---

.github/workflows/run_pre_commit.yml

This is not the off-Travis migration yet. More like warming up for that to come next :)
CC @asyncee @gauravv7

Improve pre-commit GitHub Action + enable cron mode

---

.github/workflows/run_tox.yml
tox.ini

Follow-up to PR #92 
PS: https://coveralls.io/repos/33776/builds seems to like it

Actions: Restore coveralls (follow-up to #92)

---

.github/workflows/run_tox.yml
README.rst
setup.py
tox.ini

Drop end of life Django and Python (fixes #94)

---

setup.py

Related to #94, follow-up to #95

setup.py: Drop leftover classifiers (related to #94, follow-up to #95)

---

.pre-commit-config.yaml
easy_select2/utils.py
sampleproject/demoapp/admin.py
sampleproject/demoapp/views.py
tests/test_forms.py
tests/test_utils.py
tests/test_widgets.py
tox.ini

In reaction to [CI failure](https://github.com/asyncee/django-easy-select2/actions/runs/3498480743/jobs/5858898968#step:5:21)…

pre-commit: Fix flake8 repo URL + mass-bump
